---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    name: jenkins-pvc
    namespace: jenkins
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt