apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-zookeeper-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-0
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-kafka-zookeeper-0
  namespace: kafka
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt