apiVersion: v1
data:
  jenkins.yaml: |
    jenkins:
      numExecutors: 0
      clouds:
      - kubernetes:
          containerCap: 10
          containerCapStr: "10"
          jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
          jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:80"
          name: "kubernetes"
          namespace: "jenkins"
    jobs:
      - script: >
          multibranchPipelineJob('Project') {
            displayName('Project')
              branchSources {
                  git {
                      id('19101994') 
                      remote('https://github.com/Timur-Rustamov/python-app.git')
                  }
              }
              orphanedItemStrategy {
                  discardOldItems {
                      numToKeep(20)
                  }
              }
          }  
kind: ConfigMap
metadata:
  creationTimestamp: "2021-11-28T21:09:56Z"
  name: jenkins-conf
  namespace: jenkins
  resourceVersion: "3539"
  selfLink: /api/v1/namespaces/jenkins/configmaps/jenkins-conf
  uid: 7baee8c4-a6d5-421b-b32e-7bc8513303f7

